export interface City {
  name: string;
  plateCode: number;
  latitude: number;
  longitude: number;
  latitudeDelta: number;
  longitudeDelta: number;
  districts: string[];
}

export const TURKISH_CITIES: City[] = [
  { name: 'Adana', plateCode: 1, latitude: 37.0, longitude: 35.3213, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Seyhan', 'Çukurova', 'Yüreğir', 'Sarıçam', 'Ceyhan', 'Kozan', 'İmamoğlu', 'Karaisalı', 'Pozantı', 'Aladağ', 'Feke', 'Saimbeyli', 'Tufanbeyli', 'Yumurtalık', 'Karataş'] },
  { name: 'Adıyaman', plateCode: 2, latitude: 37.7648, longitude: 38.2786, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Merkez', 'Besni', 'Kahta', 'Gölbaşı', 'Gerger', 'Samsat', 'Çelikhan', 'Sincik', 'Tut'] },
  { name: 'Afyonkarahisar', plateCode: 3, latitude: 38.7507, longitude: 30.5567, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Merkez', 'Sandıklı', 'Dinar', 'Bolvadin', 'Emirdağ', 'Sultandağı', 'Çay', 'Şuhut', 'İhsaniye', 'Sinanpaşa', 'Başmakçı', 'Bayat', 'İscehisar', 'Çobanlar', 'Evciler', 'Dazkırı', 'Hocalar', 'Kızılören'] },
  { name: 'Ağrı', plateCode: 4, latitude: 39.7191, longitude: 43.0503, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Merkez', 'Doğubayazıt', 'Patnos', 'Eleşkirt', 'Diyadin', 'Tutak', 'Hamur', 'Taşlıçay'] },
  { name: 'Amasya', plateCode: 5, latitude: 40.6499, longitude: 35.8353, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Merkez', 'Merzifon', 'Suluova', 'Taşova', 'Göynücek', 'Gümüşhacıköy', 'Hamamözü'] },
  { name: 'Ankara', plateCode: 6, latitude: 39.9334, longitude: 32.8597, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Çankaya', 'Keçiören', 'Mamak', 'Yenimahalle', 'Etimesgut', 'Sincan', 'Altındağ', 'Pursaklar', 'Gölbaşı', 'Polatlı', 'Çubuk', 'Beypazarı', 'Haymana', 'Şereflikoçhisar', 'Elmadağ', 'Kızılcahamam', 'Akyurt', 'Kalecik', 'Kazan', 'Nallıhan', 'Bala', 'Ayaş', 'Güdül', 'Evren', 'Çamlıdere'] },
  { name: 'Antalya', plateCode: 7, latitude: 36.8969, longitude: 30.7133, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Muratpaşa', 'Kepez', 'Konyaaltı', 'Aksu', 'Döşemealtı', 'Alanya', 'Manavgat', 'Serik', 'Kaş', 'Kemer', 'Kumluca', 'Finike', 'Gazipaşa', 'Demre', 'Elmalı', 'Korkuteli', 'Akseki', 'Gündoğmuş', 'İbradı'] },
  { name: 'Artvin', plateCode: 8, latitude: 41.1828, longitude: 41.8183, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Merkez', 'Hopa', 'Arhavi', 'Borçka', 'Şavşat', 'Yusufeli', 'Ardanuç', 'Murgul'] },
  { name: 'Aydın', plateCode: 9, latitude: 37.8560, longitude: 27.8416, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Efeler', 'Nazilli', 'Söke', 'Kuşadası', 'Didim', 'Çine', 'Sultanhisar', 'İncirliova', 'Germencik', 'Bozdoğan', 'Koçarlı', 'Buharkent', 'Yenipazar', 'Karacasu', 'Kuyucak', 'Köşk', 'Karpuzlu'] },
  { name: 'Balıkesir', plateCode: 10, latitude: 39.6484, longitude: 27.8826, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Altıeylül', 'Karesi', 'Bandırma', 'Edremit', 'Gönen', 'Burhaniye', 'Ayvalık', 'Bigadiç', 'Susurluk', 'Erdek', 'Dursunbey', 'Havran', 'Sındırgı', 'İvrindi', 'Manyas', 'Savaştepe', 'Kepsut', 'Balya', 'Marmara'] },
  { name: 'Bilecik', plateCode: 11, latitude: 40.0567, longitude: 30.0665, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Merkez', 'Bozüyük', 'Osmaneli', 'Söğüt', 'Gölpazarı', 'Pazaryeri', 'İnhisar', 'Yenipazar'] },
  { name: 'Bingöl', plateCode: 12, latitude: 38.8854, longitude: 40.4980, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Merkez', 'Genç', 'Solhan', 'Karlıova', 'Adaklı', 'Kiğı', 'Yayladere', 'Yedisu'] },
  { name: 'Bitlis', plateCode: 13, latitude: 38.4010, longitude: 42.1095, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Merkez', 'Tatvan', 'Ahlat', 'Güroymak', 'Hizan', 'Adilcevaz', 'Mutki'] },
  { name: 'Bolu', plateCode: 14, latitude: 40.7350, longitude: 31.6061, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Merkez', 'Mudurnu', 'Göynük', 'Mengen', 'Gerede', 'Yeniçağa', 'Dörtdivan', 'Seben', 'Kıbrıscık'] },
  { name: 'Burdur', plateCode: 15, latitude: 37.7203, longitude: 30.2908, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Merkez', 'Bucak', 'Gölhisar', 'Yeşilova', 'Ağlasun', 'Tefenni', 'Çavdır', 'Karamanlı', 'Altınyayla', 'Çeltikçi', 'Kemer'] },
  { name: 'Bursa', plateCode: 16, latitude: 40.1885, longitude: 29.0610, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Osmangazi', 'Yıldırım', 'Nilüfer', 'Gemlik', 'İnegöl', 'Mudanya', 'Karacabey', 'Orhangazi', 'Mustafakemalpaşa', 'Yenişehir', 'Gürsu', 'Kestel', 'İznik', 'Harmancık', 'Keles', 'Orhaneli', 'Büyükorhan'] },
  { name: 'Çanakkale', plateCode: 17, latitude: 40.1553, longitude: 26.4142, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Merkez', 'Biga', 'Çan', 'Gelibolu', 'Ezine', 'Ayvacık', 'Bayramiç', 'Lapseki', 'Yenice', 'Eceabat', 'Bozcaada', 'Gökçeada'] },
  { name: 'Çankırı', plateCode: 18, latitude: 40.6013, longitude: 33.6134, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Merkez', 'Çerkeş', 'Ilgaz', 'Kurşunlu', 'Şabanözü', 'Yapraklı', 'Eldivan', 'Atkaracalar', 'Kızılırmak', 'Orta', 'Bayramören', 'Korgun'] },
  { name: 'Çorum', plateCode: 19, latitude: 40.5506, longitude: 34.9556, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Merkez', 'Sungurlu', 'Osmancık', 'Alaca', 'İskilip', 'Bayat', 'Kargı', 'Mecitözü', 'Ortaköy', 'Dodurga', 'Laçin', 'Oğuzlar', 'Boğazkale', 'Uğurludağ'] },
  { name: 'Denizli', plateCode: 20, latitude: 37.7765, longitude: 29.0864, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Merkezefendi', 'Pamukkale', 'Çivril', 'Acıpayam', 'Tavas', 'Buldan', 'Çal', 'Honaz', 'Sarayköy', 'Kale', 'Serinhisar', 'Güney', 'Çameli', 'Bozkurt', 'Beyağaç', 'Baklan', 'Babadağ', 'Bekilli', 'Çardak'] },
  { name: 'Diyarbakır', plateCode: 21, latitude: 37.9144, longitude: 40.2306, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Bağlar', 'Kayapınar', 'Sur', 'Yenişehir', 'Bismil', 'Ergani', 'Çınar', 'Silvan', 'Dicle', 'Hani', 'Lice', 'Kulp', 'Hazro', 'Eğil', 'Kocaköy', 'Çermik', 'Çüngüş'] },
  { name: 'Edirne', plateCode: 22, latitude: 41.6818, longitude: 26.5623, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Merkez', 'Keşan', 'Uzunköprü', 'İpsala', 'Havsa', 'Enez', 'Süloğlu', 'Lalapaşa', 'Meriç'] },
  { name: 'Elazığ', plateCode: 23, latitude: 38.6810, longitude: 39.2264, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Merkez', 'Kovancılar', 'Karakoçan', 'Maden', 'Palu', 'Sivrice', 'Baskil', 'Ağın', 'Keban', 'Arıcak', 'Alacakaya'] },
  { name: 'Erzincan', plateCode: 24, latitude: 39.7500, longitude: 39.5000, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Merkez', 'Tercan', 'Üzümlü', 'Çayırlı', 'Refahiye', 'İliç', 'Kemah', 'Kemaliye', 'Otlukbeli'] },
  { name: 'Erzurum', plateCode: 25, latitude: 39.9055, longitude: 41.2658, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Yakutiye', 'Palandöken', 'Aziziye', 'Oltu', 'Horasan', 'Pasinler', 'İspir', 'Narman', 'Hınıs', 'Aşkale', 'Karayazı', 'Tekman', 'Tortum', 'Şenkaya', 'Olur', 'Çat', 'Karaçoban', 'Köprüköy', 'Uzundere', 'Pazaryolu'] },
  { name: 'Eskişehir', plateCode: 26, latitude: 39.7767, longitude: 30.5206, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Odunpazarı', 'Tepebaşı', 'Çifteler', 'Sivrihisar', 'Mahmudiye', 'Alpu', 'Seyitgazi', 'Sarıcakaya', 'Mihalgazi', 'Mihalıççık', 'İnönü', 'Günyüzü', 'Beylikova', 'Han'] },
  { name: 'Gaziantep', plateCode: 27, latitude: 37.0662, longitude: 37.3833, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Şahinbey', 'Şehitkamil', 'Nizip', 'İslahiye', 'Nurdağı', 'Oğuzeli', 'Araban', 'Yavuzeli', 'Karkamış'] },
  { name: 'Giresun', plateCode: 28, latitude: 40.9128, longitude: 38.3895, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Merkez', 'Bulancak', 'Espiye', 'Görele', 'Tirebolu', 'Keşap', 'Piraziz', 'Eynesil', 'Dereli', 'Yağlıdere', 'Çanakçı', 'Güce', 'Şebinkarahisar', 'Alucra', 'Çamoluk', 'Doğankent'] },
  { name: 'Gümüşhane', plateCode: 29, latitude: 40.4386, longitude: 39.5086, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Merkez', 'Kelkit', 'Şiran', 'Torul', 'Köse', 'Kürtün'] },
  { name: 'Hakkari', plateCode: 30, latitude: 37.5833, longitude: 43.7333, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Merkez', 'Yüksekova', 'Çukurca', 'Şemdinli'] },
  { name: 'Hatay', plateCode: 31, latitude: 36.4018, longitude: 36.3498, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Antakya', 'İskenderun', 'Defne', 'Arsuz', 'Payas', 'Dörtyol', 'Kırıkhan', 'Reyhanlı', 'Samandağ', 'Altınözü', 'Hassa', 'Belen', 'Erzin', 'Yayladağı', 'Kumlu'] },
  { name: 'Isparta', plateCode: 32, latitude: 37.7648, longitude: 30.5566, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Merkez', 'Yalvaç', 'Eğirdir', 'Şarkikaraağaç', 'Gelendost', 'Senirkent', 'Keçiborlu', 'Sütçüler', 'Uluborlu', 'Atabey', 'Gönen', 'Aksu', 'Yenişarbademli'] },
  { name: 'Mersin', plateCode: 33, latitude: 36.8121, longitude: 34.6415, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Akdeniz', 'Mezitli', 'Toroslar', 'Yenişehir', 'Tarsus', 'Erdemli', 'Silifke', 'Anamur', 'Mut', 'Gülnar', 'Aydıncık', 'Bozyazı', 'Çamlıyayla'] },
  { name: 'İstanbul', plateCode: 34, latitude: 41.0082, longitude: 28.9784, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Kadıköy', 'Beşiktaş', 'Şişli', 'Bakırköy', 'Üsküdar', 'Fatih', 'Beyoğlu', 'Ataşehir', 'Maltepe', 'Kartal', 'Pendik', 'Tuzla', 'Ümraniye', 'Sancaktepe', 'Sultanbeyli', 'Çekmeköy', 'Beykoz', 'Sarıyer', 'Eyüpsultan', 'Kağıthane', 'Bayrampaşa', 'Zeytinburnu', 'Güngören', 'Esenler', 'Bağcılar', 'Bahçelievler', 'Başakşehir', 'Avcılar', 'Küçükçekmece', 'Büyükçekmece', 'Beylikdüzü', 'Esenyurt', 'Arnavutköy', 'Sultangazi', 'Gaziosmanpaşa', 'Silivri', 'Çatalca', 'Şile', 'Adalar'] },
  { name: 'İzmir', plateCode: 35, latitude: 38.4189, longitude: 27.1287, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Konak', 'Karşıyaka', 'Bornova', 'Buca', 'Bayraklı', 'Çiğli', 'Gaziemir', 'Karabağlar', 'Balçova', 'Narlıdere', 'Güzelbahçe', 'Menemen', 'Torbalı', 'Ödemiş', 'Tire', 'Bergama', 'Aliağa', 'Urla', 'Çeşme', 'Seferihisar', 'Foça', 'Dikili', 'Kemalpaşa', 'Selçuk', 'Kiraz', 'Bayındır', 'Menderes', 'Beydağ', 'Karaburun', 'Kınık'] },
  { name: 'Kars', plateCode: 36, latitude: 40.6167, longitude: 43.1000, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Merkez', 'Sarıkamış', 'Kağızman', 'Digor', 'Selim', 'Arpaçay', 'Akyaka', 'Susuz'] },
  { name: 'Kastamonu', plateCode: 37, latitude: 41.3887, longitude: 33.7827, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Merkez', 'Tosya', 'Taşköprü', 'İnebolu', 'Araç', 'Çatalzeytin', 'Cide', 'Daday', 'Devrekani', 'Küre', 'Abana', 'Azdavay', 'Bozkurt', 'Doğanyurt', 'Hanönü', 'İhsangazi', 'Pınarbaşı', 'Seydiler', 'Şenpazar'] },
  { name: 'Kayseri', plateCode: 38, latitude: 38.7312, longitude: 35.4787, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Kocasinan', 'Melikgazi', 'Talas', 'Develi', 'Yahyalı', 'Bünyan', 'Tomarza', 'Pınarbaşı', 'Sarıoğlan', 'İncesu', 'Yeşilhisar', 'Felahiye', 'Özvatan', 'Akkışla', 'Hacılar', 'Sarız'] },
  { name: 'Kırklareli', plateCode: 39, latitude: 41.7333, longitude: 27.2167, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Merkez', 'Lüleburgaz', 'Babaeski', 'Vize', 'Pınarhisar', 'Demirköy', 'Kofçaz', 'Pehlivanköy'] },
  { name: 'Kırşehir', plateCode: 40, latitude: 39.1425, longitude: 34.1709, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Merkez', 'Kaman', 'Mucur', 'Çiçekdağı', 'Akpınar', 'Akçakent', 'Boztepe'] },
  { name: 'Kocaeli', plateCode: 41, latitude: 40.8533, longitude: 29.8815, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['İzmit', 'Gebze', 'Darıca', 'Çayırova', 'Dilovası', 'Körfez', 'Gölcük', 'Kartepe', 'Başiskele', 'Derince', 'Karamürsel', 'Kandıra'] },
  { name: 'Konya', plateCode: 42, latitude: 37.8746, longitude: 32.4932, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Selçuklu', 'Meram', 'Karatay', 'Ereğli', 'Akşehir', 'Seydişehir', 'Beyşehir', 'Çumra', 'Cihanbeyli', 'Kulu', 'Ilgın', 'Karapınar', 'Sarayönü', 'Bozkır', 'Hadim', 'Doğanhisar', 'Hüyük', 'Yunak', 'Tuzlukçu', 'Altınekin', 'Derebucak', 'Taşkent', 'Ahırlı', 'Çeltik', 'Derbent', 'Emirgazi', 'Güneysınır', 'Halkapınar', 'Kadınhanı', 'Yalıhüyük'] },
  { name: 'Kütahya', plateCode: 43, latitude: 39.4167, longitude: 29.9833, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Merkez', 'Tavşanlı', 'Simav', 'Gediz', 'Emet', 'Altıntaş', 'Domaniç', 'Hisarcık', 'Şaphane', 'Pazarlar', 'Aslanapa', 'Çavdarhisar', 'Dumlupınar'] },
  { name: 'Malatya', plateCode: 44, latitude: 38.3552, longitude: 38.3095, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Battalgazi', 'Yeşilyurt', 'Doğanşehir', 'Akçadağ', 'Darende', 'Hekimhan', 'Arapgir', 'Pütürge', 'Arguvan', 'Yazıhan', 'Kuluncak', 'Kale', 'Doğanyol'] },
  { name: 'Manisa', plateCode: 45, latitude: 38.6191, longitude: 27.4289, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Şehzadeler', 'Yunusemre', 'Akhisar', 'Turgutlu', 'Salihli', 'Soma', 'Alaşehir', 'Saruhanlı', 'Demirci', 'Kula', 'Gördes', 'Kırkağaç', 'Sarıgöl', 'Selendi', 'Ahmetli', 'Gölmarmara', 'Köprübaşı'] },
  { name: 'Kahramanmaraş', plateCode: 46, latitude: 37.5858, longitude: 36.9371, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Onikişubat', 'Dulkadiroğlu', 'Elbistan', 'Afşin', 'Göksun', 'Türkoğlu', 'Pazarcık', 'Andırın', 'Çağlayancerit', 'Nurhak', 'Ekinözü'] },
  { name: 'Mardin', plateCode: 47, latitude: 37.3212, longitude: 40.7245, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Artuklu', 'Kızıltepe', 'Midyat', 'Nusaybin', 'Derik', 'Mazıdağı', 'Ömerli', 'Dargeçit', 'Savur', 'Yeşilli'] },
  { name: 'Muğla', plateCode: 48, latitude: 37.2153, longitude: 28.3636, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Menteşe', 'Bodrum', 'Fethiye', 'Marmaris', 'Milas', 'Dalaman', 'Ortaca', 'Datça', 'Yatağan', 'Kavaklıdere', 'Köyceğiz', 'Ula', 'Seydikemer'] },
  { name: 'Muş', plateCode: 49, latitude: 38.9462, longitude: 41.7539, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Merkez', 'Bulanık', 'Malazgirt', 'Varto', 'Hasköy', 'Korkut'] },
  { name: 'Nevşehir', plateCode: 50, latitude: 38.6939, longitude: 34.6857, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Merkez', 'Ürgüp', 'Avanos', 'Gülşehir', 'Hacıbektaş', 'Kozaklı', 'Derinkuyu', 'Acıgöl'] },
  { name: 'Niğde', plateCode: 51, latitude: 37.9667, longitude: 34.6833, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Merkez', 'Bor', 'Çamardı', 'Ulukışla', 'Altunhisar', 'Çiftlik'] },
  { name: 'Ordu', plateCode: 52, latitude: 40.9839, longitude: 37.8764, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Altınordu', 'Ünye', 'Fatsa', 'Perşembe', 'Kumru', 'Korgan', 'Gölköy', 'Mesudiye', 'Aybastı', 'Ulubey', 'Gülyalı', 'Akkuş', 'Çamaş', 'Çatalpınar', 'Gürgentepe', 'İkizce', 'Kabadüz', 'Kabataş'] },
  { name: 'Rize', plateCode: 53, latitude: 41.0209, longitude: 40.5234, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Merkez', 'Çamlıhemşin', 'Ardeşen', 'Pazar', 'Fındıklı', 'Çayeli', 'Güneysu', 'İkizdere', 'Kalkandere', 'Derepazarı', 'Hemşin', 'İyidere'] },
  { name: 'Sakarya', plateCode: 54, latitude: 40.6940, longitude: 30.4358, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Adapazarı', 'Serdivan', 'Erenler', 'Arifiye', 'Hendek', 'Akyazı', 'Geyve', 'Karasu', 'Sapanca', 'Pamukova', 'Ferizli', 'Kaynarca', 'Söğütlü', 'Kocaali', 'Taraklı', 'Karapürçek'] },
  { name: 'Samsun', plateCode: 55, latitude: 41.2928, longitude: 36.3313, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['İlkadım', 'Atakum', 'Canik', 'Tekkeköy', 'Bafra', 'Çarşamba', 'Terme', 'Vezirköprü', 'Havza', 'Ladik', 'Kavak', 'Ayvacık', 'Alaçam', 'Yakakent', 'Salıpazarı', 'Asarcık', '19 Mayıs'] },
  { name: 'Siirt', plateCode: 56, latitude: 37.9333, longitude: 41.9500, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Merkez', 'Kurtalan', 'Baykan', 'Pervari', 'Şirvan', 'Eruh', 'Tillo'] },
  { name: 'Sinop', plateCode: 57, latitude: 42.0231, longitude: 35.1531, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Merkez', 'Boyabat', 'Gerze', 'Ayancık', 'Türkeli', 'Durağan', 'Erfelek', 'Dikmen', 'Saraydüzü'] },
  { name: 'Sivas', plateCode: 58, latitude: 39.7477, longitude: 37.0179, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Merkez', 'Şarkışla', 'Gemerek', 'Suşehri', 'Zara', 'Kangal', 'Divriği', 'Gürün', 'Yıldızeli', 'Hafik', 'Koyulhisar', 'İmranlı', 'Doğanşar', 'Altınyayla', 'Akıncılar', 'Gölova', 'Ulaş'] },
  { name: 'Tekirdağ', plateCode: 59, latitude: 41.0027, longitude: 27.5127, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Süleymanpaşa', 'Kapaklı', 'Çerkezköy', 'Çorlu', 'Ergene', 'Saray', 'Hayrabolu', 'Malkara', 'Muratlı', 'Şarköy', 'Marmaraereğlisi'] },
  { name: 'Tokat', plateCode: 60, latitude: 40.3167, longitude: 36.5544, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Merkez', 'Erbaa', 'Niksar', 'Turhal', 'Zile', 'Reşadiye', 'Almus', 'Artova', 'Pazar', 'Başçiftlik', 'Sulusaray', 'Yeşilyurt'] },
  { name: 'Trabzon', plateCode: 61, latitude: 41.0027, longitude: 39.7168, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Ortahisar', 'Akçaabat', 'Yomra', 'Arsin', 'Of', 'Araklı', 'Sürmene', 'Çaykara', 'Düzköy', 'Maçka', 'Vakfıkebir', 'Beşikdüzü', 'Tonya', 'Şalpazarı', 'Çarşıbaşı', 'Dernekpazarı', 'Hayrat', 'Köprübaşı'] },
  { name: 'Tunceli', plateCode: 62, latitude: 39.1079, longitude: 39.5401, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Merkez', 'Pertek', 'Çemişgezek', 'Hozat', 'Mazgirt', 'Nazımiye', 'Ovacık', 'Pülümür'] },
  { name: 'Şanlıurfa', plateCode: 63, latitude: 37.1591, longitude: 38.7969, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Eyyübiye', 'Haliliye', 'Karaköprü', 'Siverek', 'Viranşehir', 'Suruç', 'Akçakale', 'Birecik', 'Bozova', 'Ceylanpınar', 'Harran', 'Hilvan', 'Halfeti'] },
  { name: 'Uşak', plateCode: 64, latitude: 38.6823, longitude: 29.4082, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Merkez', 'Banaz', 'Eşme', 'Sivaslı', 'Ulubey', 'Karahallı'] },
  { name: 'Van', plateCode: 65, latitude: 38.4891, longitude: 43.4089, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['İpekyolu', 'Tuşba', 'Edremit', 'Erciş', 'Başkale', 'Çaldıran', 'Özalp', 'Gevaş', 'Gürpınar', 'Muradiye', 'Çatak', 'Bahçesaray', 'Saray'] },
  { name: 'Yozgat', plateCode: 66, latitude: 39.8181, longitude: 34.8147, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Merkez', 'Sorgun', 'Yerköy', 'Boğazlıyan', 'Akdağmadeni', 'Çekerek', 'Sarıkaya', 'Şefaatli', 'Aydıncık', 'Çandır', 'Çayıralan', 'Kadışehri', 'Saraykent', 'Yenifakılı'] },
  { name: 'Zonguldak', plateCode: 67, latitude: 41.4564, longitude: 31.7987, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Merkez', 'Ereğli', 'Çaycuma', 'Devrek', 'Alaplı', 'Gökçebey', 'Kilimli', 'Kozlu'] },
  { name: 'Aksaray', plateCode: 68, latitude: 38.3687, longitude: 34.0370, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Merkez', 'Ortaköy', 'Eskil', 'Güzelyurt', 'Gülağaç', 'Ağaçören', 'Sarıyahşi'] },
  { name: 'Bayburt', plateCode: 69, latitude: 40.2552, longitude: 40.2249, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Merkez', 'Aydıntepe', 'Demirözü'] },
  { name: 'Karaman', plateCode: 70, latitude: 37.1759, longitude: 33.2287, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Merkez', 'Ermenek', 'Sarıveliler', 'Ayrancı', 'Kazımkarabekir', 'Başyayla'] },
  { name: 'Kırıkkale', plateCode: 71, latitude: 39.8468, longitude: 33.5153, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Merkez', 'Yahşihan', 'Keskin', 'Delice', 'Sulakyurt', 'Balışeyh', 'Bahşili', 'Çelebi', 'Karakeçili'] },
  { name: 'Batman', plateCode: 72, latitude: 37.8812, longitude: 41.1351, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Merkez', 'Kozluk', 'Sason', 'Beşiri', 'Gercüş', 'Hasankeyf'] },
  { name: 'Şırnak', plateCode: 73, latitude: 37.5164, longitude: 42.4611, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Merkez', 'Cizre', 'Silopi', 'İdil', 'Uludere', 'Beytüşşebap', 'Güçlükonak'] },
  { name: 'Bartın', plateCode: 74, latitude: 41.6344, longitude: 32.3375, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Merkez', 'Amasra', 'Kurucaşile', 'Ulus'] },
  { name: 'Ardahan', plateCode: 75, latitude: 41.1105, longitude: 42.7022, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Merkez', 'Göle', 'Çıldır', 'Posof', 'Hanak', 'Damal'] },
  { name: 'Iğdır', plateCode: 76, latitude: 39.9237, longitude: 44.0450, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Merkez', 'Tuzluca', 'Aralık', 'Karakoyunlu'] },
  { name: 'Yalova', plateCode: 77, latitude: 40.6500, longitude: 29.2667, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Merkez', 'Çınarcık', 'Çiftlikköy', 'Altınova', 'Armutlu', 'Termal'] },
  { name: 'Karabük', plateCode: 78, latitude: 41.2061, longitude: 32.6204, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Merkez', 'Safranbolu', 'Eflani', 'Eskipazar', 'Yenice', 'Ovacık'] },
  { name: 'Kilis', plateCode: 79, latitude: 36.7184, longitude: 37.1212, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Merkez', 'Elbeyli', 'Musabeyli', 'Polateli'] },
  { name: 'Osmaniye', plateCode: 80, latitude: 37.0746, longitude: 36.2464, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Merkez', 'Kadirli', 'Düziçi', 'Bahçe', 'Toprakkale', 'Hasanbeyli', 'Sumbas'] },
  { name: 'Düzce', plateCode: 81, latitude: 40.8438, longitude: 31.1565, latitudeDelta: 0.08, longitudeDelta: 0.08, districts: ['Merkez', 'Akçakoca', 'Cumayeri', 'Çilimli', 'Gölyaka', 'Gümüşova', 'Kaynaşlı', 'Yığılca'] },
];

export function getCityByName(name: string): City | undefined {
  return TURKISH_CITIES.find(c => c.name === name);
}

export function getCityRegion(city: City) {
  return {
    latitude: city.latitude,
    longitude: city.longitude,
    latitudeDelta: city.latitudeDelta,
    longitudeDelta: city.longitudeDelta,
  };
}
