export interface NightlifeVenue {
  id: string;
  name: string;
  city: string;
  district?: string;
  rating: number;
  reviewCount: number;
  image: string;
  review: string;
  reviewer: string;
  category: string;
  address: string;
  safetyLevel?: 1 | 2 | 3;
}

export const SAFETY_LEVEL_INFO: { level: 1 | 2 | 3; name: string; desc: string; color: string }[] = [
  { level: 1, name: 'Güvenli İşletme', desc: '2GO QR kod & tanıtım', color: '#C8A84E' },
  { level: 2, name: 'Güvenli İşletme+', desc: '2GO indirim & aktif yönlendirme', color: '#D4A017' },
  { level: 3, name: 'Premium Güvenli', desc: '2GO alanı & tam entegrasyon', color: '#FFD700' },
];

export const ALL_NIGHTLIFE_VENUES: NightlifeVenue[] = [
  // İstanbul
  {
    id: 'ist1',
    name: 'Nusr-Et Steakhouse Etiler',
    city: 'İstanbul',
    district: 'Beşiktaş',
    rating: 4.6,
    reviewCount: 18500,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&q=80',
    review: 'Et severlerin adresi. Alkollü içecek menüsü zengin, şarap eşliğinde steakler muhteşem.',
    reviewer: 'Emre K.',
    category: 'Alkollü Restoran & Steakhouse',
    address: 'Etiler Mah., Nisbetiye Cad. No:87, Beşiktaş',
  },
  {
    id: 'ist2',
    name: 'Sunset Grill & Bar',
    city: 'İstanbul',
    district: 'Beşiktaş',
    rating: 4.7,
    reviewCount: 12400,
    image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&q=80',
    review: 'Boğaz manzarasında fine dining deneyimi. Şarap listesi ve kokteylleri ile İstanbul\'un en şık alkollü restoranı.',
    reviewer: 'Selin A.',
    category: 'Alkollü Restoran & Fine Dining',
    address: 'Ulus Mah., Yol Sok. No:2, Beşiktaş',
  },
  {
    id: 'ist3',
    name: 'Mikla Restaurant',
    city: 'İstanbul',
    district: 'Beyoğlu',
    rating: 4.8,
    reviewCount: 9800,
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&q=80',
    review: 'Türk-İskandinav füzyon mutfağı. Teras manzarası eşsiz, şarap ve kokteyl menüsü dünya standartlarında.',
    reviewer: 'Ayşe D.',
    category: 'Alkollü Restoran & Fine Dining',
    address: 'Meşrutiyet Cad. No:15, The Marmara Pera, Beyoğlu',
  },
  {
    id: 'ist4',
    name: 'Eleos Restaurant',
    city: 'İstanbul',
    district: 'Beyoğlu',
    rating: 4.6,
    reviewCount: 8700,
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&q=80',
    review: 'Rum mutfağı ve Ege lezzetleri. Şarap eşliğinde deniz ürünleri ve mezeleri harika.',
    reviewer: 'Murat T.',
    category: 'Alkollü Restoran & Bistro',
    address: 'İstiklal Cad., Beyoğlu',
  },
  {
    id: 'ist5',
    name: 'House Cafe Ortaköy',
    city: 'İstanbul',
    district: 'Beşiktaş',
    rating: 4.5,
    reviewCount: 11200,
    image: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=600&q=80',
    review: 'Boğaz kenarında brunch ve akşam yemeği. Kokteylleri ve şarap listesi çok iyi, atmosfer harika.',
    reviewer: 'Deniz B.',
    category: 'Alkollü Restoran & Cafe',
    address: 'Salhane Sok., Ortaköy, Beşiktaş',
  },
  {
    id: 'ist6',
    name: 'Lucca Bebek',
    city: 'İstanbul',
    district: 'Beşiktaş',
    rating: 4.6,
    reviewCount: 9400,
    image: 'https://images.unsplash.com/photo-1550966871-3ed3cdb51f3a?w=600&q=80',
    review: 'Bebek\'in ikonik mekanı. İtalyan mutfağı, şarap ve kokteyl eşliğinde Boğaz manzarası.',
    reviewer: 'Zeynep M.',
    category: 'Alkollü Restoran & Bistro',
    address: 'Cevdet Paşa Cad., Bebek, Beşiktaş',
  },
  {
    id: 'ist7',
    name: 'Nopa Restaurant',
    city: 'İstanbul',
    district: 'Kadıköy',
    rating: 4.5,
    reviewCount: 6200,
    image: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=600&q=80',
    review: 'Kadıköy\'ün şık bistrosu. Dünya mutfağından lezzetler, craft kokteyl ve şarap menüsü zengin.',
    reviewer: 'Kemal Y.',
    category: 'Alkollü Restoran & Bistro',
    address: 'Caferağa Mah., Moda Cad., Kadıköy',
  },

  // Ankara
  {
    id: 'ank1',
    name: 'Trilye Restaurant',
    city: 'Ankara',
    district: 'Çankaya',
    rating: 4.8,
    reviewCount: 7200,
    image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&q=80',
    review: 'Ankara\'nın en iyi balık restoranı. Şarap listesi mükemmel, deniz ürünleri ve alkol eşliğinde fine dining.',
    reviewer: 'Canan Ö.',
    category: 'Alkollü Restoran & Balık',
    address: 'Aşkabat Cad. No:16, GOP, Çankaya',
  },
  {
    id: 'ank2',
    name: 'Köşebaşı Ankara',
    city: 'Ankara',
    district: 'Çankaya',
    rating: 4.6,
    reviewCount: 5800,
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&q=80',
    review: 'Alkollü içecek servisi olan lüks kebap restoranı. Et yemekleri ve şarap eşliğinde keyifli akşamlar.',
    reviewer: 'Ali R.',
    category: 'Alkollü Restoran & Kebap',
    address: 'Filistin Sok. No:1, Gaziosmanpaşa, Çankaya',
  },
  {
    id: 'ank3',
    name: 'Mezzaluna Ankara',
    city: 'Ankara',
    district: 'Çankaya',
    rating: 4.7,
    reviewCount: 4900,
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&q=80',
    review: 'İtalyan mutfağı ve zengin şarap menüsü. Pasta ve pizza eşliğinde İtalyan şarapları mükemmel.',
    reviewer: 'Burcu T.',
    category: 'Alkollü Restoran & İtalyan',
    address: 'Arjantin Cad. No:17, Gaziosmanpaşa, Çankaya',
  },
  {
    id: 'ank4',
    name: 'La Gioia Ristorante',
    city: 'Ankara',
    district: 'Çankaya',
    rating: 4.5,
    reviewCount: 3800,
    image: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=600&q=80',
    review: 'Şık İtalyan restoranı. Şarap ve kokteyl eşliğinde romantik bir akşam yemeği için ideal.',
    reviewer: 'Onur D.',
    category: 'Alkollü Restoran & İtalyan',
    address: 'Tunalı Hilmi Cad., Kavaklıdere, Çankaya',
  },

  // İzmir
  {
    id: 'izm1',
    name: 'Deniz Restaurant',
    city: 'İzmir',
    district: 'Konak',
    rating: 4.7,
    reviewCount: 8800,
    image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&q=80',
    review: 'Kordon\'da deniz manzaralı alkollü restoran. Balık ve Ege mezeleri şarap eşliğinde harika.',
    reviewer: 'Ece Y.',
    category: 'Alkollü Restoran & Balık',
    address: 'Atatürk Cad., Kordon, Konak',
  },
  {
    id: 'izm2',
    name: 'Velvet Cafe & Restaurant',
    city: 'İzmir',
    district: 'Konak',
    rating: 4.6,
    reviewCount: 5400,
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&q=80',
    review: 'Alsancak\'ın sevilen bistrosu. Dünya mutfağı, kokteyl ve şarap menüsü ile keyifli akşamlar.',
    reviewer: 'Pınar G.',
    category: 'Alkollü Restoran & Bistro',
    address: 'Kıbrıs Şehitleri Cad., Alsancak, Konak',
  },
  {
    id: 'izm3',
    name: 'Sakız Restaurant',
    city: 'İzmir',
    district: 'Konak',
    rating: 4.8,
    reviewCount: 6200,
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&q=80',
    review: 'Ege mutfağının en iyi temsilcisi. Zeytinyağlılar, deniz ürünleri ve şarap eşliğinde mükemmel yemek.',
    reviewer: 'Can S.',
    category: 'Alkollü Restoran & Ege Mutfağı',
    address: '1382 Sok., Alsancak, Konak',
  },
  {
    id: 'izm4',
    name: 'Gümüşlük Restoran',
    city: 'İzmir',
    district: 'Karşıyaka',
    rating: 4.5,
    reviewCount: 4100,
    image: 'https://images.unsplash.com/photo-1550966871-3ed3cdb51f3a?w=600&q=80',
    review: 'Karşıyaka sahilinde balık ve meze. Alkollü içecek menüsü zengin, deniz manzarası eşsiz.',
    reviewer: 'Tolga M.',
    category: 'Alkollü Restoran & Balık',
    address: 'Cemal Gürsel Cad., Karşıyaka',
  },

  // Antalya
  {
    id: 'ant1',
    name: 'Seraser Fine Dining',
    city: 'Antalya',
    district: 'Muratpaşa',
    rating: 4.8,
    reviewCount: 7200,
    image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&q=80',
    review: 'Kaleiçi\'nde tarihi konakta fine dining. Şarap listesi olağanüstü, Akdeniz mutfağı muhteşem.',
    reviewer: 'Mehmet A.',
    category: 'Alkollü Restoran & Fine Dining',
    address: 'Tuzcular Mah., Karanlık Sok. No:18, Kaleiçi, Muratpaşa',
  },
  {
    id: 'ant2',
    name: 'Vanilla Restaurant',
    city: 'Antalya',
    district: 'Muratpaşa',
    rating: 4.6,
    reviewCount: 5100,
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&q=80',
    review: 'Lara\'da şık alkollü restoran. Uluslararası mutfak, kokteyl ve şarap ile keyifli akşamlar.',
    reviewer: 'Elif T.',
    category: 'Alkollü Restoran & Bistro',
    address: 'Lara Cad., Muratpaşa',
  },
  {
    id: 'ant3',
    name: '7 Mehmet Restaurant',
    city: 'Antalya',
    district: 'Muratpaşa',
    rating: 4.7,
    reviewCount: 9800,
    image: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=600&q=80',
    review: 'Antalya\'nın efsane restoranı. Türk mutfağı, manzara ve alkollü içecek seçenekleri ile tam bir deneyim.',
    reviewer: 'Seda K.',
    category: 'Alkollü Restoran & Türk Mutfağı',
    address: 'Meltem Mah., Atatürk Kültür Parkı Yanı, Muratpaşa',
  },

  // Bursa
  {
    id: 'brs1',
    name: 'Kebapçı İskender (Atatürk Cad.)',
    city: 'Bursa',
    district: 'Osmangazi',
    rating: 4.7,
    reviewCount: 14200,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&q=80',
    review: 'Bursa\'nın ikonik restoranı. İskender kebap yanında alkollü içecek seçenekleri de mevcut.',
    reviewer: 'Gül H.',
    category: 'Alkollü Restoran & Kebap',
    address: 'Atatürk Cad., Osmangazi',
  },
  {
    id: 'brs2',
    name: 'Kitap Evi Restaurant',
    city: 'Bursa',
    district: 'Osmangazi',
    rating: 4.6,
    reviewCount: 5100,
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&q=80',
    review: 'Tarihi Osmanlı konağında şarap eşliğinde yemek. Bursa manzarası ve atmosferi büyüleyici.',
    reviewer: 'Fatma N.',
    category: 'Alkollü Restoran & Bistro',
    address: 'Tophane, Osmangazi',
  },
  {
    id: 'brs3',
    name: 'Uludağ Kebapçısı Cemal & Cemil',
    city: 'Bursa',
    district: 'Osmangazi',
    rating: 4.5,
    reviewCount: 6800,
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&q=80',
    review: 'Bursa kebabının en iyi adreslerinden. Alkollü içecek servisi ile akşam yemeği için ideal.',
    reviewer: 'Osman B.',
    category: 'Alkollü Restoran & Kebap',
    address: 'Çekirge Cad., Osmangazi',
  },

  // Denizli
  {
    id: 'dnz1',
    name: 'Garson Şükrü',
    city: 'Denizli',
    district: 'Pamukkale',
    safetyLevel: 2,
    rating: 4.7,
    reviewCount: 4200,
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&q=80',
    review: 'Denizli\'nin efsane alkollü restoranı. Limonlu kavurma, zeytinyağlılar ve geniş rakı seçkisi ile harika geceler.',
    reviewer: 'Elif K.',
    category: 'Alkollü Restoran & Bistro',
    address: 'Gökpınar Mah., Atatürk Blv. No:33, Pamukkale',
  },
  {
    id: 'dnz2',
    name: 'Moi Restaurant',
    city: 'Denizli',
    district: 'Pamukkale',
    rating: 4.6,
    reviewCount: 3100,
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&q=80',
    review: 'Modern ve şık alkollü restoran. Dünya mutfağından lezzetler, kokteyl ve şarap eşliğinde keyifli akşamlar.',
    reviewer: 'Ahmet Y.',
    category: 'Alkollü Restoran & Bistro',
    address: 'Kınıklı Mah., 15 Mayıs Cad., Pamukkale',
  },
  {
    id: 'dnz3',
    name: 'Tefli Restaurant',
    city: 'Denizli',
    district: 'Merkezefendi',
    rating: 4.5,
    reviewCount: 2800,
    image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&q=80',
    review: 'Denizli\'nin sevilen alkollü meyhane & bistrosu. Meze çeşitleri ve rakı seçenekleri ile keyifli akşamlar.',
    reviewer: 'Zeynep K.',
    category: 'Alkollü Restoran & Meyhane',
    address: 'Bahçelievler Mah., 53. Sok., Merkezefendi',
  },
  {
    id: 'dnz4',
    name: 'Çamlık Marina Restaurant',
    city: 'Denizli',
    district: 'Merkezefendi',
    rating: 4.4,
    reviewCount: 1900,
    image: 'https://images.unsplash.com/photo-1550966871-3ed3cdb51f3a?w=600&q=80',
    review: 'Çamlık\'ta doğa içinde alkollü restoran. Balık ve et menüsü zengin, şarap seçenekleri güzel.',
    reviewer: 'Murat B.',
    category: 'Alkollü Restoran & Balık',
    address: 'Mehmetçik Mah., Çamlık Blv. No:58, Merkezefendi',
  },
  {
    id: 'dnz5',
    name: 'Eat\'n Joy',
    city: 'Denizli',
    district: 'Merkezefendi',
    rating: 4.6,
    reviewCount: 1047,
    image: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=600&q=80',
    review: 'Çamlaraltı\'nda şık alkollü restoran. Geniş menü, kokteyl ve bira seçenekleri ile keyifli ortam.',
    reviewer: 'Serkan A.',
    category: 'Alkollü Restoran & Bistro',
    address: '6015. Sok. No:5, Çamlaraltı, Merkezefendi',
  },

  // Gaziantep
  {
    id: 'gaz1',
    name: 'Orkide Restaurant',
    city: 'Gaziantep',
    district: 'Şahinbey',
    rating: 4.6,
    reviewCount: 4500,
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&q=80',
    review: 'Gaziantep mutfağı ve alkollü içecek bir arada. Kebap ve lahmacun yanında şarap keyfi.',
    reviewer: 'Mustafa E.',
    category: 'Alkollü Restoran & Antep Mutfağı',
    address: 'Suburcu Mah., Şahinbey',
  },
  {
    id: 'gaz2',
    name: 'Bayazhan Restaurant',
    city: 'Gaziantep',
    district: 'Şahinbey',
    rating: 4.7,
    reviewCount: 5200,
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&q=80',
    review: 'Tarihi handa alkollü restoran deneyimi. Antep mutfağı lezzetleri, şarap ve atmosfer muhteşem.',
    reviewer: 'Aylin C.',
    category: 'Alkollü Restoran & Antep Mutfağı',
    address: 'Boyacı Mah., Şahinbey',
  },
  {
    id: 'gaz3',
    name: 'Papirüs Restaurant & Bistro',
    city: 'Gaziantep',
    district: 'Şehitkamil',
    rating: 4.5,
    reviewCount: 3100,
    image: 'https://images.unsplash.com/photo-1550966871-3ed3cdb51f3a?w=600&q=80',
    review: 'Şık alkollü bistro. Antep lezzetleri ve dünya mutfağı bir arada, kokteyl menüsü başarılı.',
    reviewer: 'Nalan T.',
    category: 'Alkollü Restoran & Bistro',
    address: 'İncilipınar Mah., Şehitkamil',
  },

  // Trabzon
  {
    id: 'trb1',
    name: 'Cemilusta Balık Restaurant',
    city: 'Trabzon',
    district: 'Ortahisar',
    rating: 4.7,
    reviewCount: 5400,
    image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&q=80',
    review: 'Trabzon\'un en iyi balık restoranı. Taze Karadeniz balığı, alkollü içecek seçenekleri ile lezzet şöleni.',
    reviewer: 'İbrahim Ç.',
    category: 'Alkollü Restoran & Balık',
    address: 'Sahil Yolu, Ortahisar',
  },
  {
    id: 'trb2',
    name: 'Bordo Mavi Restaurant',
    city: 'Trabzon',
    district: 'Ortahisar',
    rating: 4.5,
    reviewCount: 3200,
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&q=80',
    review: 'Deniz manzaralı alkollü restoran. Karadeniz mutfağı ve balık çeşitleri, şarap eşliğinde harika.',
    reviewer: 'Fatih Y.',
    category: 'Alkollü Restoran & Karadeniz Mutfağı',
    address: 'Forum Trabzon Yanı, Ortahisar',
  },

  // Konya
  {
    id: 'kon1',
    name: 'Hünkar Restaurant',
    city: 'Konya',
    district: 'Selçuklu',
    rating: 4.3,
    reviewCount: 2200,
    image: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=600&q=80',
    review: 'Konya\'da alkollü içecek servisi yapan restoran. Et yemekleri ve şarap seçenekleri mevcut.',
    reviewer: 'Ahmet Ç.',
    category: 'Alkollü Restoran',
    address: 'Büsan Organize, Selçuklu',
  },
  {
    id: 'kon2',
    name: 'Tiritçi Mithat',
    city: 'Konya',
    district: 'Selçuklu',
    rating: 4.2,
    reviewCount: 1800,
    image: 'https://images.unsplash.com/photo-1550966871-3ed3cdb51f3a?w=600&q=80',
    review: 'Konya mutfağı ve alkollü içecek bir arada. Otel bünyesinde konforlu bir restoran deneyimi.',
    reviewer: 'Yusuf K.',
    category: 'Alkollü Restoran',
    address: 'Özalan Mah., Selçuklu',
  },

  // Eskişehir
  {
    id: 'esk1',
    name: 'Sımıt Bistro',
    city: 'Eskişehir',
    district: 'Odunpazarı',
    rating: 4.6,
    reviewCount: 4800,
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&q=80',
    review: 'Eskişehir\'in en sevilen alkollü bistrosu. Dünya mutfağı lezzetleri, şarap ve kokteyl ile keyifli akşamlar.',
    reviewer: 'Berk T.',
    category: 'Alkollü Restoran & Bistro',
    address: 'Odunpazarı Evleri Yanı, Odunpazarı',
  },
  {
    id: 'esk2',
    name: 'Traverten Restaurant',
    city: 'Eskişehir',
    district: 'Tepebaşı',
    rating: 4.5,
    reviewCount: 3600,
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&q=80',
    review: 'Porsuk kenarında alkollü restoran. Et ve balık menüsü zengin, şarap listesi başarılı.',
    reviewer: 'Gizem A.',
    category: 'Alkollü Restoran & Bistro',
    address: 'Porsuk Bulvarı, Tepebaşı',
  },
  {
    id: 'esk3',
    name: 'Arasta Bazaar Restaurant',
    city: 'Eskişehir',
    district: 'Tepebaşı',
    rating: 4.4,
    reviewCount: 2900,
    image: 'https://images.unsplash.com/photo-1550966871-3ed3cdb51f3a?w=600&q=80',
    review: 'Tarihi çarşıda modern alkollü restoran. Türk ve dünya mutfağı, kokteyl ve şarap eşliğinde.',
    reviewer: 'Deniz K.',
    category: 'Alkollü Restoran & Bistro',
    address: 'Porsuk Çayı Kenarı, Tepebaşı',
  },

  // Muğla / Bodrum
  {
    id: 'mug1',
    name: 'Limon Bistro Bodrum',
    city: 'Muğla',
    district: 'Bodrum',
    rating: 4.8,
    reviewCount: 8400,
    image: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=600&q=80',
    review: 'Bodrum\'un en şık alkollü bistrosu. Akdeniz mutfağı, kokteyl ve şarap ile gün batımında muhteşem.',
    reviewer: 'Aslı M.',
    category: 'Alkollü Restoran & Bistro',
    address: 'Yalıkavak Marina, Bodrum',
  },
  {
    id: 'mug2',
    name: 'Orfoz Restaurant',
    city: 'Muğla',
    district: 'Bodrum',
    rating: 4.7,
    reviewCount: 6800,
    image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&q=80',
    review: 'Deniz kenarında taze balık ve şarap. Bodrum\'un en iyi alkollü balık restoranlarından.',
    reviewer: 'Ceren D.',
    category: 'Alkollü Restoran & Balık',
    address: 'Göltürkbükü, Bodrum',
  },
  {
    id: 'mug3',
    name: 'Memedof Bistro',
    city: 'Muğla',
    district: 'Bodrum',
    rating: 4.6,
    reviewCount: 5200,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&q=80',
    review: 'Bodrum merkezde şık alkollü restoran. Ege lezzetleri ve kokteyl menüsü çok başarılı.',
    reviewer: 'Sinem T.',
    category: 'Alkollü Restoran & Bistro',
    address: 'Neyzen Tevfik Cad., Bodrum',
  },

  // Adana
  {
    id: 'adn1',
    name: 'Yüzevler Restaurant',
    city: 'Adana',
    district: 'Seyhan',
    rating: 4.6,
    reviewCount: 5400,
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&q=80',
    review: 'Adana\'nın en bilinen alkollü restoranı. Adana kebabı ve şarap eşliğinde muhteşem yemek deneyimi.',
    reviewer: 'Taner K.',
    category: 'Alkollü Restoran & Kebap',
    address: 'Tepebağ Mah., Seyhan',
  },
  {
    id: 'adn2',
    name: 'Ciğerci Memet Usta',
    city: 'Adana',
    district: 'Seyhan',
    rating: 4.5,
    reviewCount: 3800,
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&q=80',
    review: 'Adana ciğer kebabının en iyi adresi. Alkollü içecek servisi de mevcut, lezzet garantisi.',
    reviewer: 'Volkan S.',
    category: 'Alkollü Restoran & Kebap',
    address: 'Çakmak Cad., Seyhan',
  },

  // Diyarbakır
  {
    id: 'diy1',
    name: 'Sülüklü Han Restaurant',
    city: 'Diyarbakır',
    district: 'Sur',
    rating: 4.5,
    reviewCount: 3200,
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&q=80',
    review: 'Tarihi handa alkollü restoran deneyimi. Yöresel lezzetler ve şarap ile otantik bir atmosfer.',
    reviewer: 'Serdar B.',
    category: 'Alkollü Restoran & Yöresel',
    address: 'Suriçi, Gazi Cad., Sur',
  },
  {
    id: 'diy2',
    name: 'Diyar Bistro',
    city: 'Diyarbakır',
    district: 'Yenişehir',
    rating: 4.4,
    reviewCount: 2100,
    image: 'https://images.unsplash.com/photo-1550966871-3ed3cdb51f3a?w=600&q=80',
    review: 'Diyarbakır\'ın modern alkollü bistrosu. Dünya mutfağı ve yöresel lezzetler, kokteyl seçenekleri iyi.',
    reviewer: 'Rojda A.',
    category: 'Alkollü Restoran & Bistro',
    address: 'Ofis Mah., Yenişehir',
  },

  // Kayseri
  {
    id: 'kay1',
    name: 'Erciyes Steak & Wine',
    city: 'Kayseri',
    district: 'Melikgazi',
    rating: 4.4,
    reviewCount: 2800,
    image: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=600&q=80',
    review: 'Erciyes manzarasında steak ve şarap. Kayseri\'nin şık alkollü restoranı, et menüsü çok iyi.',
    reviewer: 'Erdem Y.',
    category: 'Alkollü Restoran & Steakhouse',
    address: 'Cumhuriyet Mah., Melikgazi',
  },

  // Mersin
  {
    id: 'mer1',
    name: 'Sahil Balık Restaurant',
    city: 'Mersin',
    district: 'Akdeniz',
    rating: 4.6,
    reviewCount: 4200,
    image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&q=80',
    review: 'Mersin sahilinde alkollü balık restoranı. Taze balık ve Akdeniz mezeleri, şarap eşliğinde harika.',
    reviewer: 'Gökhan T.',
    category: 'Alkollü Restoran & Balık',
    address: 'Sahil Yolu, Akdeniz',
  },

  // Hatay
  {
    id: 'hat1',
    name: 'Sultan Sofrası Restaurant',
    city: 'Hatay',
    district: 'Antakya',
    rating: 4.7,
    reviewCount: 4600,
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&q=80',
    review: 'Hatay mutfağının en iyi temsilcisi. Humus, kebap ve alkollü içecekler ile muhteşem bir sofra.',
    reviewer: 'Lina H.',
    category: 'Alkollü Restoran & Hatay Mutfağı',
    address: 'Uzun Çarşı, Antakya',
  },
  {
    id: 'hat2',
    name: 'Liwan Hotel Restaurant',
    city: 'Hatay',
    district: 'Antakya',
    rating: 4.6,
    reviewCount: 3400,
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&q=80',
    review: 'Tarihi Antakya evinde alkollü restoran. Yerel lezzetler ve şarap, atmosferi büyüleyici.',
    reviewer: 'Musa K.',
    category: 'Alkollü Restoran & Boutique',
    address: 'Silahlı Kuvvetler Cad., Antakya',
  },

  // Samsun
  {
    id: 'sam1',
    name: 'Piazza Restaurant',
    city: 'Samsun',
    district: 'İlkadım',
    rating: 4.5,
    reviewCount: 3200,
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&q=80',
    review: 'Samsun\'un en sevilen alkollü restoranı. Karadeniz lezzetleri ve taze balık, şarap eşliğinde.',
    reviewer: 'Cem A.',
    category: 'Alkollü Restoran & Balık',
    address: 'Sahil Mah., İlkadım',
  },

  // Aydın
  {
    id: 'ayd1',
    name: 'Marina Restaurant Kuşadası',
    city: 'Aydın',
    district: 'Efeler',
    rating: 4.5,
    reviewCount: 3600,
    image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&q=80',
    review: 'Deniz manzaralı alkollü restoran. Ege mezeleri ve balık, şarap eşliğinde yaz gecelerinin keyfi.',
    reviewer: 'Derya Ö.',
    category: 'Alkollü Restoran & Balık',
    address: 'Marina, Efeler',
  },

  // Manisa
  {
    id: 'man1',
    name: 'Manisa Bağ Evi Restaurant',
    city: 'Manisa',
    district: 'Şehzadeler',
    rating: 4.4,
    reviewCount: 2100,
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&q=80',
    review: 'Manisa\'nın bağ kültürünü yaşatan alkollü restoran. Yerel şaraplar ve yöresel yemekler harika.',
    reviewer: 'Kaan M.',
    category: 'Alkollü Restoran & Yöresel',
    address: 'Merkez, Şehzadeler',
  },
];

export function getNightlifeVenuesByCity(city: string, district?: string): NightlifeVenue[] {
  const cityVenues = ALL_NIGHTLIFE_VENUES.filter(
    (v) => v.city.toLowerCase() === city.toLowerCase()
  );
  if (district && cityVenues.some(v => v.district?.toLowerCase() === district.toLowerCase())) {
    const districtVenues = cityVenues.filter(
      (v) => v.district?.toLowerCase() === district.toLowerCase()
    );
    if (districtVenues.length >= 3) return districtVenues;
  }
  return cityVenues;
}

export const DENIZLI_NIGHTLIFE_VENUES: NightlifeVenue[] = ALL_NIGHTLIFE_VENUES.filter(v => v.city === 'Denizli');
